### ISSUE TITLE
Install in a clean conda environment fails on python > 3.10

### ISSUE THREAD

**Issue by AoifeHughes** [PandemiaProject/pandemia#7]
Steps to reproduce the issue: 

1. Clone via git 
2. Create a conda environment:
    - `conda create -n pandemia-test` 
    - `conda activate pandemia-test` 
    - `conda install pip`
3. As per current instructions, run `pip install .` which raises
```bash 
    (pandemia-test) ➜  pandemia git:(main) pip install .
Processing /Users/ahughes/git/pandemia
  Preparing metadata (setup.py) ... done
Collecting tqdm~=4.64
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting numpy~=1.23
  Using cached numpy-1.23.4-cp311-cp311-macosx_11_0_arm64.whl (13.3 MB)
Collecting scipy~=1.8
  Using cached scipy-1.9.3-cp311-cp311-macosx_12_0_arm64.whl (28.4 MB)
Collecting matplotlib~=3.5
  Downloading matplotlib-3.6.2-cp311-cp311-macosx_11_0_arm64.whl (7.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 11.5 MB/s eta 0:00:00
Collecting pyproj~=3.3
  Using cached pyproj-3.4.0-cp311-cp311-macosx_11_0_arm64.whl (3.8 MB)
Collecting joblib~=1.1
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 12.9 MB/s eta 0:00:00
Collecting pyshp~=2.3
  Downloading pyshp-2.3.1-py2.py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.5/46.5 kB 4.0 MB/s eta 0:00:00
Collecting pygame~=2.1
  Downloading pygame-2.1.2.tar.gz (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 11.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]


      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using Darwin configuration...

      /bin/sh: sdl2-config: command not found
      /bin/sh: sdl2-config: command not found
      /bin/sh: sdl2-config: command not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/f4/m42_v8vj1fjc0wrwtb69xjt80000gr/T/pip-install-w205xlui/pygame_c13f3e0d0e7b4b3a82c13f57fed4fcdf/setup.py", line 359, in <module>
          buildconfig.config.main(AUTO_CONFIG)
        File "/private/var/folders/f4/m42_v8vj1fjc0wrwtb69xjt80000gr/T/pip-install-w205xlui/pygame_c13f3e0d0e7b4b3a82c13f57fed4fcdf/buildconfig/config.py", line 225, in main
          deps = CFG.main(**kwds)
                 ^^^^^^^^^^^^^^^^
        File "/private/var/folders/f4/m42_v8vj1fjc0wrwtb69xjt80000gr/T/pip-install-w205xlui/pygame_c13f3e0d0e7b4b3a82c13f57fed4fcdf/buildconfig/config_darwin.py", line 132, in main
          [DependencyProg('SDL', 'SDL_CONFIG', 'sdl2-config', '2.0', ['sdl'])],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/f4/m42_v8vj1fjc0wrwtb69xjt80000gr/T/pip-install-w205xlui/pygame_c13f3e0d0e7b4b3a82c13f57fed4fcdf/buildconfig/config_unix.py", line 39, in __init__
          self.ver = config[0].strip()
                     ~~~~~~^^^
      IndexError: list index out of range

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/MacCompile
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
``` 

System info: 
- Python 3.11
- macOS 12.6.1
- Apple M1 Pro CPU

**Comment by AoifeHughes** [comment]
This might be very specific for Macs and installing one of the requirements `pygame` requiring a few extra steps: https://www.pygame.org/wiki/MacCompile 

Still, I'm wondering/checking if there's a nice way to resolve this issue that makes it easier for all platforms.

**Comment by AoifeHughes** [comment]
Interesting - this is a python >3.10 issue. 

I repeated the above steps but specified the python version to be 3.10 and install works fine.

**Comment by AoifeHughes** [comment]
Doesn't seem to be a huge issue and the readme already specifies this, but maybe good to make clear that it will not work with other versions of python currently?
