### ISSUE TITLE
Multiple ModuleNotFound errors when running through readme.md

### ISSUE THREAD

**Issue by AoifeHughes** [PandemiaProject/pandemia#8]
Post installing as per instructions and running: 

```
pandemia Scenarios/Global/global_config.yaml
```

I get: 

```
(pandemia310) ➜  pandemia git:(readme_tweaks) pandemia Scenarios/Global/global_config.yaml

Traceback (most recent call last):
  File "/usr/local/Caskroom/miniforge/base/envs/pandemia310/bin/pandemia", line 5, in <module>
    from pandemia import main
  File "/usr/local/Caskroom/miniforge/base/envs/pandemia310/lib/python3.10/site-packages/pandemia/__init__.py", line 11, in <module>
    from pandemia.sim_factory import SimulationFactory
  File "/usr/local/Caskroom/miniforge/base/envs/pandemia310/lib/python3.10/site-packages/pandemia/sim_factory.py", line 13, in <module>
    from pandemia.config import Config
  File "/usr/local/Caskroom/miniforge/base/envs/pandemia310/lib/python3.10/site-packages/pandemia/config.py", line 12, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by AoifeHughes** [comment]
I can resolve this through:

``` pip install pyyaml ``` 

But then a new error is raised: 

```
(pandemia310) ➜  pandemia git:(install_tweaks) ✗ pandemia Scenarios/Global/global_config.yaml

Traceback (most recent call last):
  File "/usr/local/Caskroom/miniforge/base/envs/pandemia310/bin/pandemia", line 5, in <module>
    from pandemia import main
  File "/usr/local/Caskroom/miniforge/base/envs/pandemia310/lib/python3.10/site-packages/pandemia/__init__.py", line 11, in <module>
    from pandemia.sim_factory import SimulationFactory
  File "/usr/local/Caskroom/miniforge/base/envs/pandemia310/lib/python3.10/site-packages/pandemia/sim_factory.py", line 18, in <module>
    from pandemia.components.seasonal_effects_model import SeasonalEffectsModel
ModuleNotFoundError: No module named 'pandemia.components'
(pandemia310) ➜  pandemia git:(install_tweaks) ✗
```

Perhaps some linking in the modules needs to be checked? (Looking into now)

**Comment by AoifeHughes** [comment]
Using branch: https://github.com/PandemiaProject/pandemia/tree/install_tweaks to resolve these issues when a solution is reached

**Comment by AoifeHughes** [comment]
Just to clarify - I ran this on a Windows 11 VM to test if it was a Mac specific issue and the same problem is still appearing

```
(pandemia) PS Z:\Documents\win_pandemia\pandemia-main> pandemia Scenarios/Global/global_config.yaml
Traceback (most recent call last):
  File "C:\Users\ahughes\anaconda3\envs\pandemia\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ahughes\anaconda3\envs\pandemia\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ahughes\anaconda3\envs\pandemia\Scripts\pandemia.exe\__main__.py", line 4, in <module>
  File "C:\Users\ahughes\anaconda3\envs\pandemia\lib\site-packages\pandemia\__init__.py", line 11, in <module>
    from pandemia.sim_factory import SimulationFactory
  File "C:\Users\ahughes\anaconda3\envs\pandemia\lib\site-packages\pandemia\sim_factory.py", line 18, in <module>
    from pandemia.components.seasonal_effects_model import SeasonalEffectsModel
ModuleNotFoundError: No module named 'pandemia.components'
(pandemia) PS Z:\Documents\win_pandemia\pandemia-main>
```

**Comment by James-Thompson-724** [comment]
Ah, ok I'm currently looking into this

**Comment by James-Thompson-724** [comment]
Ok, try installing using

pip install -e .[test]

**Comment by AoifeHughes** [comment]
I've some ideas :) Currently in meetings, but will hopefully have a fix soonish *
